/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoTextColor: typeof import('./src/components/AutoTextColor.vue')['default']
    AutoTextColorExample: typeof import('./src/components/AutoTextColorExample.vue')['default']
    DocLoadErrorIllustration: typeof import('./src/components/icons/DocLoadErrorIllustration.vue')['default']
    DocOutlineIcon: typeof import('./src/components/icons/DocOutlineIcon.vue')['default']
    DocsEmptyIllustration: typeof import('./src/components/icons/DocsEmptyIllustration.vue')['default']
    FullScreenModal: typeof import('./src/components/FullScreenModal/index.vue')['default']
    LucideIcon: typeof import('./src/components/LucideIcon/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDropdown: typeof import('./src/components/SelectDropdown/index.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
  }
}
