/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Lumi API
 * @description Description
 * @version 1.0.0
}
**/

import { defHttp } from "../axios/http";
import type { RequestOptions } from "../axios/interface";

export const getStorageInfo = (options: RequestOptions = {}) => {
  return defHttp.request<any>(
    {
      url: `/storageInfo`,
      method: "get",
      params: {},
      data: {}
    },
    options
  );
};
